"""add_voice_sample_embedding_cache

Revision ID: 078627c881c3
Revises: 2868f56ede2b
Create Date: 2026-09-08 23:24:20.726670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '078627c881c3'
down_revision: Union[str, Sequence[str], None] = '2868f56ede2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicesample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicesample', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
