"""add last_reminder_prompts to email settings

Revision ID: 0b2631571f72
Revises: dbcc2af3183a
Create Date: 2026-08-21 15:25:26.041009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0b2631571f72'
down_revision: Union[str, Sequence[str], None] = 'dbcc2af3183a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_prompts', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailsettings', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_prompts')

    # ### end Alembic commands ###
