"""repurpose_add_thbm_rotation_fields

Revision ID: 31418d15bd21
Revises: 0b2631571f72
Create Date: 2026-09-02 18:41:28.472882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '31418d15bd21'
down_revision: Union[str, Sequence[str], None] = '0b2631571f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funnel_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('hook_posture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('length_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('structural_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('media_pairing', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('media_pairing')
        batch_op.drop_column('structural_format')
        batch_op.drop_column('length_bucket')
        batch_op.drop_column('hook_posture')
        batch_op.drop_column('funnel_stage')

    # ### end Alembic commands ###
