"""add scheduled_week and configurable email day/time

Revision ID: 542566dd4872
Revises: 17bb7fa6b3e0
Create Date: 2026-08-17 01:24:41.891225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '542566dd4872'
down_revision: Union[str, Sequence[str], None] = '17bb7fa6b3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'09:00'"), nullable=False))
        batch_op.add_column(sa.Column('digest_day', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Sunday'"), nullable=False))
        batch_op.add_column(sa.Column('digest_time', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'12:00'"), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('scheduled_week')

    with op.batch_alter_table('emailsettings', schema=None) as batch_op:
        batch_op.drop_column('digest_time')
        batch_op.drop_column('digest_day')
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
