"""weekly template auto prepare

Revision ID: 5762dca53fe9
Revises: e9758bfd207c
Create Date: 2026-10-02 20:49:34.764184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5762dca53fe9'
down_revision: Union[str, Sequence[str], None] = 'e9758bfd207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeklytemplate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_prepare', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeklytemplate', schema=None) as batch_op:
        batch_op.drop_column('auto_prepare')

    # ### end Alembic commands ###
