"""add_voice_sample_question

Revision ID: 6515eb9df41b
Revises: 5bcca3137f6e
Create Date: 2026-09-04 00:13:03.363530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6515eb9df41b'
down_revision: Union[str, Sequence[str], None] = '5bcca3137f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicesample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicesample', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###
