"""add_weekly_template_and_bank_link

Revision ID: d49a5125d289
Revises: 38d872cfac60
Create Date: 2026-09-03 11:58:59.894885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd49a5125d289'
down_revision: Union[str, Sequence[str], None] = '38d872cfac60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklytemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tuesday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wednesday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thursday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('friday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saturday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sunday', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommend_holidays', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plannednote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plannednote_source_bank_id_topicbank', 'topicbank', ['source_bank_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plannednote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plannednote_source_bank_id_topicbank', type_='foreignkey')
        batch_op.drop_column('source_bank_id')

    op.drop_table('weeklytemplate')
    # ### end Alembic commands ###
