"""add planned_note table

Revision ID: dbcc2af3183a
Revises: 542566dd4872
Create Date: 2026-08-21 14:38:34.105400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dbcc2af3183a'
down_revision: Union[str, Sequence[str], None] = '542566dd4872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plannednote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plannednote')
    # ### end Alembic commands ###
