"""add calendar events

Revision ID: fcccb1177342
Revises: 078627c881c3
Create Date: 2026-10-02 15:11:35.089245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fcccb1177342'
down_revision: Union[str, Sequence[str], None] = '078627c881c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('angle_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('suggestion_made', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topicbank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_topicbank_calendar_event_id', 'calendarevent', ['calendar_event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topicbank', schema=None) as batch_op:
        batch_op.drop_constraint('fk_topicbank_calendar_event_id', type_='foreignkey')
        batch_op.drop_column('embedding')
        batch_op.drop_column('calendar_event_id')

    op.drop_table('calendarevent')
    # ### end Alembic commands ###
