"""add api usage counter and email settings

Revision ID: 17bb7fa6b3e0
Revises: faca3aea6259
Create Date: 2026-08-16 23:05:05.305174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '17bb7fa6b3e0'
down_revision: Union[str, Sequence[str], None] = 'faca3aea6259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiusagecounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tavily_calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailsettings')
    op.drop_table('apiusagecounter')
    # ### end Alembic commands ###
