"""level 4: add hashtags, tags, suggested_day, sources, compliance_note to posts

Revision ID: 8124847f1d14
Revises: 5ec17dddc924
Create Date: 2026-08-14 11:48:26.097190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8124847f1d14'
down_revision: Union[str, Sequence[str], None] = '5ec17dddc924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtags', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('suggested_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sources', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('compliance_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('compliance_note')
        batch_op.drop_column('sources')
        batch_op.drop_column('suggested_day')
        batch_op.drop_column('tags')
        batch_op.drop_column('hashtags')

    # ### end Alembic commands ###
