"""The original example text from the brand template file, as filled slots - used to
check the app's template copies render the same as the originals."""

SAMPLES = {
    "statement": {"label": "Point of view", "headline": "Automate the task,", "headline_gold": "not the job."},
    "quote": {"label": "In my words", "quote": "I stopped writing the Friday update. It just goes out -", "quote_gold": "and it sounds like me."},
    "big_number": {"label": "Build 01 · Result", "before_value": "6h", "after_value": "40m",
                   "caption": "A weekly content task, before and after one automated pipeline.",
                   "stats": ["3 channels", "1 approval step", "0 copy-paste"]},
    "before_after": {"label": "Before / after", "headline": "Same task.", "headline_gold": "Different Friday.",
                     "before": ["Copy notes into three apps", "Rewrite it for every channel", "Chase people for approval", "Guess what actually worked"],
                     "after": ["The event logs itself", "Drafts appear, in your voice", "You tap approve", "A dashboard shows results"]},
    "list": {"label": "Field notes · 5 rules", "headline": "Five rules before you", "headline_gold": "automate anything.",
             "items": ["Pick the task you'd happily never do again.", "Write down what “done” looks like.",
                       "Keep one human checkpoint.", "Measure hours saved, not features.", "Ship it small, then let it grow."]},
    "myth_fact": {"label": "Myth / fact", "myth": "You need a big team to use AI well.", "fact": "One well-built pipeline beats",
                  "fact_gold": "ten AI tools.", "fact_line": "Start with one task. Automate it end to end."},
    "announcement": {"label": "Now booking", "headline": "Two founding-client spots", "headline_gold": "this quarter.",
                     "button": "Free 20-min scope call →"},
    "how_it_works": {
        "label": "Carousel · How it works", "headline": "How I turn one task into", "headline_gold": "a system.",
        "subline": "Three steps. Nothing for you to manage.",
        "steps": [{"name": "Scope", "line": "A 20-minute call to pick the one task worth automating first."},
                  {"name": "Build", "line": "I build the whole pipeline. You approve; you don't manage."},
                  {"name": "Report", "line": "A dashboard shows what ran and the time it saved."}],
        "you_bring": "One task that eats your week.", "strip": ["Event", "Drafts", "Review", "Posted"], "strip_you": 3,
        "dashboard_title": "Dashboard · this week",
        "dashboard": [{"label": "Runs", "value": "14"}, {"label": "Hours saved", "value": "5.3"}, {"label": "Approved", "value": "14 / 14"}],
        "cta_headline": "Got a task that", "cta_gold": "eats your week?", "cta_button": "Free 20-min scope call →"},
    "case_study": {
        "label": "Case study · Build 01", "headline": "One event in.", "headline_gold": "Five channels out.",
        "subline": "How one automated pipeline cut a weekly content task from 6 hours to 40 minutes.",
        "problem_headline": "Six hours a week of", "problem_gold": "copy, paste, rewrite.",
        "problems": ["Notes lived in one place, posts in three others.", "Every channel needed its own rewrite.", "Nobody knew which posts actually worked."],
        "build_headline": "Five steps,", "build_gold": "one approval.",
        "build_steps": [{"name": "Event", "desc": "A milestone gets logged"}, {"name": "AI drafts", "desc": "LinkedIn · WhatsApp · Facebook"},
                        {"name": "You review", "desc": "Edit or approve - the only manual step"}, {"name": "Published", "desc": "Posted across channels"},
                        {"name": "Tracked", "desc": "The stats page updates itself"}],
        "you_step": 3, "before_value": "6h", "after_value": "40m", "result_caption": "Weekly content work, before and after.",
        "result_stats": [{"value": "3", "label": "Channels covered"}, {"value": "1", "label": "Human step left"}],
        "lesson": "The AI was the easy part.", "lesson_gold": "The handoff was the work.",
        "lesson_line": "Design the human checkpoint first. Everything else is plumbing.",
        "cta_headline": "Want this", "cta_gold": "for your week?", "cta_button": "Book a free scope call →"},
}
